[package]
name = "recruitment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
csv = "1.3.0"
rust_decimal = { version = "1.35.0", features = ["serde-with-str"] }
serde = { version = "1.0.203", features = ["derive"] }
